version: "3"
services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.3
    entrypoint: /usr/local/bin/etcd
    command:
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls=http://0.0.0.0:2380"
      - "--initial-cluster=default=http://0.0.0.0:2380"
      - "--advertise-client-urls=http://0.0.0.0:2379"
    ports:
      - 2379:2379
      - 2380:2380
