workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - test
  - deploy

unit_tests:
  tags:
    - testenv
  stage: test
  script:
    - testenv -v unit-test --ci-cd ${PWD}
  artifacts:
    paths:
      - static
    expire_in: 1 day

# используем pages для отображения coverage
pages:
  stage: deploy
  tags:
    - testenv
  dependencies:
    - unit_tests
  script:
      - rm -rf public
      - mkdir -p public
      - cp static/coverage.html ./public/coverage.html
  artifacts:
    paths:
      - public
    expire_in: 7 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'